name: event_bus_exception
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  image_network: ^2.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
